# Generated by Django 3.1.3 on 2020-12-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='datetime',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
